import Head from 'next/head'
import dynamic from 'next/dynamic'
import { css } from '@emotion/css'

const HomePage = dynamic(() => import('../src/components/pages/Home'), {
  ssr: false
})

const cssContainer = css`
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  height: 100vh;
`

export default function Home() {

  return (
    <div className={cssContainer}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomePage/>
    </div>
  )
}
