nodeLinker: node-modules

npmScopes:
  psycholog-studio:
    npmRegistryServer: "https://npm.pkg.github.com"
  tokileecy:
    npmRegistryServer: "https://npm.pkg.github.com"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

unsafeHttpWhitelist:
  - npm.pkg.github.com

yarnPath: .yarn/releases/yarn-3.1.1.cjs
