nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.1.1.cjs

unsafeHttpWhitelist:
  - npm.pkg.github.com

npmScopes:
  tokileecy:
    npmRegistryServer: "https://npm.pkg.github.com"
  psycholog-studio:
    npmRegistryServer: "https://npm.pkg.github.com"