name: lint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@psycholog-studio'
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 6.0.2
      - name: set package token
        run: |
          echo "${PSYCHOLOG_NPM_TOKEN}"
          pnpm config set @psycholog-studio https://npm.pkg.github.com/
          pnpm config set @tokileecy https://npm.pkg.github.com/
          pnpm config set -- '//npm.pkg.github.com/:_authToken' "$PSYCHOLOG_NPM_TOKEN"
        env:
          PSYCHOLOG_NPM_TOKEN: ${{ secrets.PSYCHOLOG_NPM_TOKEN }}
      - name: eslint check
        run: |
          pnpm i --reporter=silent
          pnpm eslint:check

