name: Deploy Legacy Exhibit to Firebase Hosting

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'apps/toki-website-legacy/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/toki-website-legacy
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - uses: pnpm/action-setup@v4
        with:
          version: 7
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TOKILEECY_WEBSITE }}'
          channelId: live
          projectId: tokileecy-website
          target: legacy
